job/urls.py
from django.conf.urls import url
import job.views

urlpatterns = [
    
    #url(r'^$', 'job.views.jobs'),
    url(r'^(?P<job_id>\d+)/$', job.views.job_detail),
    url(r'^(?P<job_id>\d+)/applicants/$', job.views.applicantlist),
    url(r'^add/$', job.views.jobForm),
    url(r'^edit/(?P<job_id>\d+)/$', job.views.editJobForm),
    url(r'^apply/$', job.views.applyJob),
    url(r'^search/$', job.views.jobsearch),
    url(r'^list/(?P<student_id>\d+)/$', job.views.jobList),
    url(r'^delete/(?P<job_id>\d+)/$', job.views.deleteJob),
       
]
    

needanerd/urls.py
from django.conf.urls import url, include
import needanerd.views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

permission_denied_url = '/denied/'

urlpatterns = [
               
    # (r'^test/', TemplateView.as_view(template_name="bstemplate.html")),
    url(r'^students/', include('student.urls')),
    url(r'^employers/', include('employer.urls')),
    url(r'^jobs/', include('job.urls')),
    url(r'^resumes/', include('resume.urls')),
    url(r'^accounts/', include('appsecurity.urls')),
    #url(r'^messages/', include('msgcenter.urls')),
    
    url(r'^contact/$', needanerd.views.contact),
    url(r'^contact/(?P<user_id>\d+)/$', needanerd.views.contactUserForm),

    url(r'^profile/', needanerd.views.profile, name='profile'),
 
    url(r'^$', needanerd.views.home, name='home'),
    url(r'^/$', needanerd.views.home, name='home'),
    url(r'^', 'needanerd.views.notfound', name='404'),
]

appsecurity/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.contrib import admin

# import the logging library
import logging
# Get an instance of a logger
logger = logging.getLogger()

class UserProfile(models.Model):
        
    user = models.OneToOneField(User)
    activation_key = models.CharField(null=True, blank=True, max_length=256)
    key_expires=models.DateTimeField(null=True, blank=True)

admin.site.register(UserProfile)

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
        #UserProfile.objects.create(user=instance)
        
post_save.connect(create_user_profile, sender=User)

job/models.py
#from django.contrib.auth.models import User
from django.db import models
from django import forms
from django.utils.translation import ugettext_lazy as _
from datetime import datetime
from django.contrib.auth.models import User
from django.contrib import admin
from django.utils.datastructures import MultiValueDictKeyError

# import the logging library
import logging
# Get an instance of a logger
logger = logging.getLogger('NeedANerd.custom')

'This class is used to serialize a JSON response back to the user through the search REST functions'
class JobSearch(models.Model):
    jobpk=models.CharField(max_length=32)
    studentpk=models.CharField(max_length=32, blank=True)
    name=models.CharField(max_length=32)
    applied=models.BooleanField()
    employer=models.CharField(max_length=32)
    employerpk=models.CharField(max_length=32)
    salary=models.CharField(max_length=32)
    updated_at=models.CharField(max_length=32)

class Job(models.Model):
    
    #studentwatch=models.ManyToManyField('student.Student', blank=True)
    applicant=models.ManyToManyField('student.Student', blank=True)
    employer=models.ForeignKey('employer.Employer')
    name=models.CharField(max_length=32)
    description=models.CharField(max_length=3200)
    skills=models.CharField(max_length=1000)
    #startdate = models.CharField(max_length=16)
    #enddate = models.CharField(max_length=16)
    startdate = models.DateField()
    enddate = models.DateField(null=True, blank=True)
    salary=models.CharField(max_length=16)
    released = models.BooleanField(null=False, blank=False, default=True)
    #Used on first create
    created_at = models.DateTimeField(auto_now_add = True)
    #Auto add everytime the object is resaved
    updated_at = models.DateTimeField(auto_now = True)

admin.site.register(Job)

class JobForm(forms.ModelForm):

    name = forms.CharField(label="*Position", max_length=32, widget=forms.TextInput(attrs={'placeholder':''}))
    description = forms.CharField(label="*Description", widget=forms.widgets.Textarea(attrs={'rows':16, 'cols':100, 'placeholder':''}))
    skills = forms.CharField(label="*Skills", widget=forms.widgets.Textarea(attrs={'rows':4, 'cols':50, 'placeholder':''}))
    salary = forms.CharField(label="Salary Information", max_length=16, required=False,widget=forms.TextInput(attrs={'placeholder':''}))
    released = forms.BooleanField(label = "Release for Viewing",widget=forms.CheckboxInput(),initial=True,required=False)    
        
    class Meta:
        model = Job
        exclude = ("applicant","employer","startdate","enddate")
        
    def save(self, employerpk):
        
        logger.debug('Saving a new job')
        logger.debug('employerpk='+str(employerpk))
        logger.debug('self.instance.pk='+str(self.instance.pk))
        if self.instance.pk:
            job=Job.objects.get(pk=self.instance.pk)
        else:
            job = Job()
            
        job.name=self.cleaned_data['name']
        job.description=self.cleaned_data['description']
        job.skills=self.cleaned_data['skills']
        
        startdatestr=self.data['startdate']
        startdatearr = startdatestr.split('/')
        startmonth = startdatearr[0]
        startyear = startdatearr[1]
        job.startdate = startyear + "-" + startmonth + "-01"
        
        logger.debug('job.startdate='+job.startdate)
        
        try:
            permposition=self.data['permposition']
            #job.enddate=''
            logger.debug('Permenant position job.enddate='+str(job.enddate))
        except MultiValueDictKeyError:
            job.enddate=self.data['enddate']
            logger.debug('job.enddate='+job.enddate)
        
        try:
            enddatestr=self.data['enddate']
            enddatearr = enddatestr.split('/')
            endmonth = enddatearr[0]
            endyear = enddatearr[1]
            job.enddate = endyear + "-" + endmonth + "-01"
        except MultiValueDictKeyError:
            job.enddate = None
        except IndexError:
            job.enddate = None
                
        job.salary=self.cleaned_data['salary']
        job.released=self.cleaned_data['released']
        user=User.objects.get(pk=employerpk)
        job.employer = user.userprofile.employer
        logger.debug('Adding job to employer, company name = '+user.userprofile.employer.company_name)
        job.save()
        
        return job

job/views.py
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import get_object_or_404, render_to_response
from django.db.models import Q 
from django.template import RequestContext
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core import serializers
from django.contrib.auth.decorators import user_passes_test, login_required
from job.models import Job, JobForm, JobSearch#, JobEditForm
from resume.models import Resume
from needanerd.views import isStudent, isEmployer
from needanerd import studentgroupname, employergroupname
from needanerd.urls import permission_denied_url
from django.utils.datastructures import MultiValueDictKeyError
from student.models import Student
from datetime import datetime
from django.forms.forms import NON_FIELD_ERRORS
from django.conf import settings
import operator
import logging
from threading import Thread

# Get an instance of a logger
logger = logging.getLogger('NeedANerd.custom')

def notifyStudentsNewJob(job):

    studentList=User.objects.filter(groups__name=studentgroupname).order_by('last_name')
    
    logger.debug('Now notifying %s students of the new posting',studentList.count())
            
    subject = 'Need a Nerd Notification: '+job.name+' apply now!'
    message = 'Hello Nerd, There is a new job posting.  Login to need a nerd for details\n'+settings.HOST+'/jobs/'+str(job.pk)
    for s in studentList:
        recipient=s.email
        logger.debug('Sending notification email to '+recipient)
        from django.core.mail import send_mail
        send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [recipient])
        
@login_required
def jobsearch(request):
    
    if 'str' in request.GET:
        strval = request.GET['str']
            
    logger.debug('Search for jobs based up on search string='+strval)
    
    #userList=User.objects.filter(groups__name=groups.studentgroupname).filter(Q(first_name__contains=strval) |
    #                                                                          Q(last_name__contains=strval )).order_by('last_name')
    
    search_args = []
    for term in strval.split():
        for query in ('name__icontains', 'employer__company_name__icontains', 'skills__icontains', 'description__icontains'):
            search_args.append(Q(**{query: term}))

    jobList = Job.objects.filter(reduce(operator.or_, search_args))
    
    js = []
    for job in jobList:
        appliedValue=False
        if isStudent(request.user):
            studentpk=str(request.user.pk)
            if job in request.user.userprofile.student.job_set.all():
                appliedValue=True
        'There is a probably a better way to do this but I am getting tired'
        user=User.objects.select_related().filter(userprofile__employer__job__pk=job.pk).get()
        datestr=job.updated_at.strftime('%b')
        datestr=datestr.upper()
        datestr+=job.updated_at.strftime(' %d %Y')
        if studentpk:
            obj = JobSearch(jobpk=str(job.pk), studentpk=studentpk, name=job.name, employer=job.employer.company_name, employerpk=user.pk, salary=job.salary, applied=appliedValue, updated_at=datestr)
        else:
            obj = JobSearch(jobpk=str(job.pk), name=job.name, employer=job.employer.company_name, employerpk=user.pk, salary=job.salary, applied=appliedValue, updated_at=datestr)
        js.append(obj)
        
    logger.debug('Found %s jobs',jobList.count())
    json_serializer = serializers.get_serializer("json")()
    response = json_serializer.serialize(js)
    return HttpResponse(response)

@login_required
@user_passes_test(isStudent, login_url=permission_denied_url)
def applyJob(request):
    user = request.user
    e = User.objects.filter(groups__name=employergroupname)
    
    resumes=Resume.objects.filter(student=user.userprofile.student)[:1]
    if resumes:
        resume=resumes[0]
    else:
        resume=None    
    
    joblist = Job.objects.filter(released=True).order_by('-updated_at')
    paginator = Paginator(joblist, 5) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        j = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        j = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        j = paginator.page(paginator.num_pages)
     
    return render_to_response('applyjobs.html', {'student': user, 'jobs': j, 'employers': e, 'resume': resume}, context_instance=RequestContext(request))

@login_required
def jobList(request, student_id):
    
    u = get_object_or_404(User, pk=student_id)
    
    if isStudent(u):
        logger.debug('Found student with user id=%d',u.id)
        joblist = u.userprofile.student.job_set.all()
        msg = 'You have applied to the following positions'
    else:
        joblist = Job.objects.filter(released=True).order_by('-updated_at')
    
    paginator = Paginator(joblist, 5) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        j = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        j = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        j = paginator.page(paginator.num_pages)

    return render_to_response('listjobs.html', {'msg': msg, 'student': u, 'jobs': j}, context_instance=RequestContext(request))

@login_required
def job_detail(request, job_id):
    logger.debug("job_detail called")
    j = get_object_or_404(Job, pk=job_id)
    
    user=request.user
    resumes=Resume.objects.filter(student=user.userprofile.student)[:1]
    if resumes:
        resume=resumes[0]
    else:
        resume=None
    
    logger.debug('Student(s) found for the job')
    form = JobForm(instance=j) # An unbound form    
    return render_to_response('job_detail.html', {'job': j, 'student': user, 'resume': resume, 'form': form, 'startdate': j.startdate, 'enddate': j.enddate}, context_instance=RequestContext(request))

@login_required
def applicantlist(request, job_id):
    
    logger.debug("ApplicantList called")
    j = get_object_or_404(Job, pk=job_id)

    if not j.employer.pk == request.user.userprofile.employer.pk:
        return HttpResponseForbidden()

    applicants = Student.objects.filter(job__pk=j.pk)
    logger.debug('Found ' + str(len(applicants)) + ' applicant(s) for job id='+str(j.pk));
    paginator = Paginator(applicants, 5) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        a = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        a = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        a = paginator.page(paginator.num_pages)

    logger.debug('Job.name='+j.name);
    return render_to_response('listapplicants.html', {'applicants': a, 'job': j}, context_instance=RequestContext(request))


@login_required
@user_passes_test(isEmployer, login_url=permission_denied_url)
def deleteJob(request, job_id):
    logger.debug("deleteJob called")
    j = get_object_or_404(Job, pk=job_id)
    response = HttpResponse('')
    if j.employer.pk == request.user.userprofile.employer.pk:
        j.delete()
        logger.debug('Job Deleted')
        response.write("Job Deleted")
    else:        
        response.write("You are not authorized to delete this job")
        response.status_code=401
        logger.debug('Returning a 401 unauthorized')
    return HttpResponse(response)

def checkdates(form):
            
        logger.debug('checkdates called')
        
        startdate=form.data['startdate']
        if not startdate:
            logger.debug('Startdate not provided')
            form.date_errors = 'Start date not provided'
            return False
        
        permposition=form.data.get('permposition', False)
        if permposition:
            logger.debug('This is a permenant position')
            return True
        
        enddate=form.data['enddate']
        logger.debug('startdate='+str(startdate))
        logger.debug('enddate='+enddate)
        
        startdatearr = startdate.split('/')
        startmonth = startdatearr[0]
        startyear = startdatearr[1]
        startdatenew = startmonth + "/01/" + startyear
        
        try:
            enddatearr = enddate.split('/')
            endmonth = enddatearr[0]
            endyear = enddatearr[1]
            enddatenew = endmonth + "/01/" + endyear
        except MultiValueDictKeyError:
            form.date_errors="ERROR: You must provide a start date and an end date unless this is a permenant position"
            logger.debug(form.date_errors)
            return False
        except IndexError:
            form.date_errors="ERROR: You must provide a start date and an end date unless this is a permenant position"
            logger.debug(form.date_errors)
            return False
                    
        start = datetime.strptime(startdatenew, '%m/%d/%Y')
        end = datetime.strptime(enddatenew, '%m/%d/%Y')
        if end < datetime.now():
            form.date_errors="ERROR: The end date cannot be before the current date"
            logger.debug(form.date_errors)
            return False
            #raise forms.ValidationError("You cannot enter an end date in the past") 
        elif end < start:
            form.date_errors="ERROR: The start date cannot be after the end date"
            logger.debug(form.date_errors)
            return False
            #raise forms.ValidationError("End date cannot be before start date")
        else:
            return True
        
@login_required
@user_passes_test(isEmployer, login_url=permission_denied_url)
def jobForm(request):

job/templates/addjob.html
{% extends "need_a_nerd_base.html" %}

{% load bootstrap3 %}

{% block title %}Add a Job{% endblock %}

{% block content %}

<div class='register'>
	
	<p>
		<form action="/jobs/add/" method="post" role="form">
		{% csrf_token %}
	{% if form.errors %}
	<br/>
    {% for field in form %}
        {% for error in field.errors %}
           		<div class="alert alert-danger">
                <strong>{{ error|escape }}: {{field.label}}</strong>
            </div>
        {% endfor %}
    {% endfor %}
	{% endif %}
	{% if form.date_errors %}
	<br/>
    <div class="alert alert-danger">
                <strong>{{form.date_errors}}</strong>
                </div>
    {% endif %}
	
		<div id="newjob">
		
			{% csrf_token %}
   			{% bootstrap_form form %}
			
			<div class="fieldWrapper">
	        	{{ form.startdate.errors }}
	        	<label for="startdate" class="required">*Start Date:</label>
	        	<input type="text" id="startdate" name="startdate" />
	    	</div>
	    
	    	<br />
	    
	    	<div class="fieldWrapper">
	        	{{ form.enddate.errors }}
	        		<label for="enddate" >End Date: &nbsp;</label>
	        		<input type="text" id="enddate" name="enddate" />
	        		<br />
	        		
	        		
	        </div>
	        <label class="control-label">Permenant Position</label>
	        <input id="permposition" name="permposition" type="checkbox" />
	    	<br /><br />
	    		
	    	<p>
	    	<button type="submit" class="btn-lg btn-primary">
	    		<span class="glyphicon glyphicon-ok-sign"></span> Post Job	
			</button>
		
		</div>
		
		</p>
	</form>
</div>
{% endblock %}
	

job/templates/applyjobs.html
{% extends "need_a_nerd_base.html" %}

{% block title %}Jobs{% endblock %}

{% block content %}
{% if jobs %}

	<form id='searchjobs'>
		<br/>
		<label for="jobsearchstr" class="control-label">Keyword Search: Search job name, employer, description, or skills (partial searches accepted)</label>
		<div class="row">	
			<div class="col-md-4">
				<p>
					<input type=text id='jobsearchstr' onkeydown=searchJobs(''+document.getElementById("jobsearchstr").value+'') placeholder="Software Engineer" />
				</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6">
				<button class="btn btn-primary" type=submit >Show All Jobs</button>
			</div>
		</div>
		<br />
	</form>
	<br />
	
	<div class="table-responsive">
	<table id='applyjobstable' class="table table-striped table-hover table-responsive">
	<tr>
		<th>Details</th>
    	<th>Name</th>
        <th>Employer</th>
           	<th class="visible-md visible-lg">Salary</th>
        	<th class="visible-sm visible-md visible-lg">Apply</th>
        	<th class="visible-md visible-lg">Posting Date</th>
        </span>
	</tr>
	{% for j in jobs %}
    	<tr width="100%" onmouseover="this.style.backgroundColor='#ffff66';" onmouseout="this.style.backgroundColor='#d4e3e5';">
        	<td class="visible-sm visible-md visible-lg"><button class="btn btn-primary" onclick="window.open('/jobs/{{j.pk}}/')">Show Details</button>
        	<td class="visible-xs"><button class="btn btn-primary" onclick="window.open('/jobs/{{j.pk}}/')">Details</button>
        	<td>{{j.name}}</td>
        	<td><a href='/employers/{{j.employer.userprofile.user.pk}}/'>{{j.employer.company_name}}</a></td>
	        	<td class="visible-md visible-lg">{{j.salary}}</td>
	        	{% if student.userprofile.student in j.applicant.all %}
	        		<td class="visible-sm visible-md visible-lg"><button class="btn btn-success" id=jobid_{{j.pk}} disabled=True>Applied</button></td>
	        	{% else %}
	        		<td class="visible-sm visible-md visible-lg"><button class="btn btn-primary" id=jobid_{{j.pk}} onClick="applyJob(objective='{{resume.objective|length}}', email='{{student.email|length}}', major='{{student.userprofile.student.currentmajor|length}}', jobid={{j.pk}}, studentid={{student.pk}})">Apply</button></td>
	        	{% endif %}        	
	        	<td class="visible-md visible-lg">{{j.updated_at|date:'b d Y '|upper}}</td>
    	</tr>
	{% endfor %}
	</table>
	</div>
	<small>
	<p id="top10" class="text-left"></p>
	</small>
<div id="pagination" class="pagination">
<span class="step-links">
        {% if jobs.has_previous %}
            <a href="?page={{ jobs.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ jobs.number }} of {{ jobs.paginator.num_pages }}.
        </span>

        {% if jobs.has_next %}
            <a href="?page={{ jobs.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>
{% else %}
    There are no students listed in the database.
{% endif %}
{% endblock %}

job/templates/editjob.html
{% extends "need_a_nerd_base.html" %}

{% load bootstrap3 %}

{% block title %}Edit a Job{% endblock %}

{% block content %}

<div class='register'>
	<p>
		<form action="/jobs/edit/{{jobid}}/" method="post">
		{% csrf_token %}	
		{% if form.errors %}
	<br/>
    {% for field in form %}
        {% for error in field.errors %}
           		<div class="alert alert-danger">
                <strong>{{ error|escape }}: {{field.label}}</strong>
            </div>
        {% endfor %}
    {% endfor %}
	{% endif %}
	{% if form.date_errors %}
	<br/>
    <div class="alert alert-danger">
                <strong>{{form.date_errors}}</strong>
                </div>
    {% endif %}
	
		<div id="newjob">
		
			{% csrf_token %}
   			{% bootstrap_form form %}
			
			<div class="fieldWrapper">
	        	{{ form.startdate.errors }}
	        	<label for="startdate" class="required">*Start Date:</label>
	        	<input type="text" id="startdate" name="startdate" value="{{startdate|date:'m/Y'}}" />
	    	</div>
	    
	    	<br />
	    
	    	<div class="fieldWrapper">
	        	{{ form.enddate.errors }}
	        		<label for="enddate" >End Date: &nbsp;</label>
	        		<input type="text" id="enddate" name="enddate" value="{{enddate|date:'m/Y'}}" />
	        		<br />
	        		
	        		
	        </div>
	        <label class="control-label">Permenant Position</label>
	        {% if not enddate %}
	        	<input id="permposition" name="permposition" type="checkbox" checked/>
	        {% else %}
	        	<input id="permposition" name="permposition" type="checkbox" />
	        {% endif %}	        
	        <br /><br />
	    		
	    	<p>
	    	<input type="hidden" name="employerid" value="{{employer.pk}}"></input>
	    	<button type="submit" class="btn-lg btn-primary">
	    		<span class="glyphicon glyphicon-ok-sign"></span> Save Changes	
			</button>
		
		</div>
		
		</p>
	</form>
</div>
{% endblock %}
	

job/templates/job_detail.html
{% extends "need_a_nerd_base.html" %}

{% block title %}Applicants{% endblock %}

{% block content %}

{% if job %}

	<table class="table table-hover table-responsive">
	<tr width="100%">
    	<td>Employer:</td>
    	<td>{{job.employer.company_name}}</td>
    </tr>
	<tr width="100%">
    	<td>Name:</td>
    	<td>{{job.name}}</td>
    </tr>
	<tr width="100%">
    	<td>Description:</td>
    	<td>{{job.description}}</td>
    </tr>
    <tr width="100%">
    	<td>Skills:</td>
    	<td>{{job.skills}}</td>
    </tr>
    <tr width="100%">
    	<td>Start Date:</td>
    	<td>{{job.startdate|date:'F, Y'}}</td>
    </tr>
    <tr width="100%">
    	<td>End Date:</td>
    	{% if job.enddate %}
    		<td>{{job.enddate|date:'F, Y'}}</td>
    	{% else %}
    		<td>This is a permenant position</td>
    	{% endif %}
    </tr>
    <tr width="100%">
    	<td>Salary:</td>
    	{% if job.salary %}
		<td>{{job.salary}}</td>
		{% else %}
		<td>N/A</td>
		{% endif %}
    </tr>
    <tr width="100%">
    	<td>Last Updated:</td>
    	<td>{{job.updated_at|date:'b d Y'|upper}}</td>
    </tr>
    </table>
    
    {% if user.userprofile.student in job.applicant.all %}
    	<button class="btn btn-success" id=jobid_{{job.pk}} disabled=True>Applied</button>
    {% else %}
    	<button class="btn btn-primary" id=jobid_{{job.pk}} onClick="applyJob(objective='{{resume.objective|length}}', email='{{student.email|length}}', major='{{student.userprofile.student.currentmajor|length}}', jobid={{job.pk}}, studentid={{user.pk}})">Apply</button>
    {% endif %}        	
        	
    
	{% ifequal user.pk job.employer.userprofile_set.get.user.pk %}
		
		<br /><br />
		{% if students %}
			<div style='font-style:italic;'>
				<p>Applicants:</p>
			</div>
			<table class="table table-striped table-hover table-responsive">
			<tr width="100%">
		    	<th>Name</th>
		    	<th>Academic Major</th>
		        <th>Username</th>
		        <th>Email</th>
			</tr>
			{% for s in students %}	
				<tr width="100%" onmouseover="this.style.backgroundColor='#ffff66';" onmouseout="this.style.backgroundColor='#d4e3e5';">
			   	<td>{{s.first_name}} {{s.last_name}}</td>
			    <td>{{s.userprofile.student.currentmajor}}</td>
			    <td>{{s.username}}</td>
				<td>{{s.email}}</td>		        	
			</tr>
			{% endfor %}
			</table>
		{% else %}
		
		There are no students currently applied for this position
		{% endif %}
	{% endifequal %}
{% endif %} 
{% endblock %}

job/templates/listapplicants.html
{% extends "need_a_nerd_base.html" %}

{% block title %}All Students{% endblock %}

{% block content %}

{% if applicants %}

	<br />
	<label for="applicantstable" class="control-label">Nerds that applied to be a {{job.name}}</label>
	<br /><br />
	<div class="table-responsive">
	<table id="applicantstable" class="table table-striped table-hover">
	<tr>
    	<th>Name</th>
    	<th class="visible-md visible-lg">Academic Major</th>
    	<th class="visible-xs visible-sm">Major</th> 
        <th class="visible-sm visible-md visible-lg">Email</th>
        <th>Contact Student</th>
        <!-- <th>Add Review</th>
         -->
	</tr>
	{% for user in applicants  %}
    	<tr>
        	<td><a href='/students/{{user.pk}}/'>{{user.userprofile.user.first_name}} {{user.userprofile.user.last_name}}</a></td>
        	<td>{{user.currentmajor}}</td>
        	<td class="visible-sm visible-md visible-lg">{{user.userprofile.user.email}}</td>
        	<td><a class="btn btn-primary" href="/contact/{{user.pk}}/">Contact</a></td>
        	<!-- <td><button class="btn btn-primary" onclick="window.location='/studentreview/{{user.pk}}/'" >Add Review</button></td> -->
    	</tr>
	{% endfor %}
	</table>
	</div>
	<small>
	<p id="top10" class="text-left"></p>
	</small>
	<div id="pagination" class="pagination">
	    <span class="step-links">
	        {% if applicants.has_previous %}
	            <a href="?page={{ applicants.previous_page_number }}">Previous</a>
	        {% endif %}
	
	        <span class="current">
	            Page {{ applicants.number }} of {{ applicants.paginator.num_pages }}.
	        </span>
	
	        {% if applicants.has_next %}
	            <a href="?page={{ applicants.next_page_number }}">Next</a>
	        {% endif %}
	    </span>
	</div>
{% else %}
    There are no applicants for this position
{% endif %}
{% endblock %}

job/templates/listjobs.html
{% extends "need_a_nerd_base.html" %}

{% block title %}Jobs{% endblock %}

{% block content %}

{% if student %}

{% endif %}

{% if jobs %}
	<div>
		<table class="table table-striped table-hover table-responsive">
		<tr width="100%">
	    	<th>Details</th>
	    	<th>Name</th>
	        <th>Description</th>
	        <th>Employer</th>
	        <th>Posting Date</th>
		</tr>
		{% for j in jobs %}
			<tr>
	        	<td><button class="btn btn-primary" onclick="window.open('/jobs/{{j.pk}}/')">Show Details</button></td>
	        	<td>{{j.name}}</td>
	        	<td>{{j.description|slice:":512"}}</td>
	        	<td><a href='/employers/{{j.employer.userprofile.user.pk}}/'>{{j.employer.company_name}}</td>
	        	<td>{{j.updated_at|date:'b d Y '|upper}}</td>
	    	</tr>
	    {% endfor %}
		</table>
	</div>
<br />
<div class="pagination">
    <span class="step-links">
        {% if jobs.has_previous %}
            <a href="?page={{ jobs.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ jobs.number }} of {{ jobs.paginator.num_pages }}.
        </span>

        {% if jobs.has_next %}
            <a href="?page={{ jobs.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>
{% else %}
There are no jobs listed on Need a Nerd
{% endif %}
{% endblock %}