job/urls.py
from django.conf.urls import url
import job.views

urlpatterns = [
    
    #url(r'^$', 'job.views.jobs'),
    url(r'^(?P<job_id>\d+)/$', job.views.job_detail),
    url(r'^(?P<job_id>\d+)/applicants/$', job.views.applicantlist),
    url(r'^add/$', job.views.jobForm),
    url(r'^edit/(?P<job_id>\d+)/$', job.views.editJobForm),
    url(r'^apply/$', job.views.applyJob),
    url(r'^search/$', job.views.jobsearch),
    url(r'^list/(?P<student_id>\d+)/$', job.views.jobList),
    url(r'^delete/(?P<job_id>\d+)/$', job.views.deleteJob),
       
]
    

needanerd/urls.py
from django.conf.urls import url, include
import needanerd.views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

permission_denied_url = '/denied/'

urlpatterns = [
               
    # (r'^test/', TemplateView.as_view(template_name="bstemplate.html")),
    url(r'^students/', include('student.urls')),
    url(r'^employers/', include('employer.urls')),
    url(r'^jobs/', include('job.urls')),
    url(r'^resumes/', include('resume.urls')),
    url(r'^accounts/', include('appsecurity.urls')),
    #url(r'^messages/', include('msgcenter.urls')),
    
    url(r'^contact/$', needanerd.views.contact),
    url(r'^contact/(?P<user_id>\d+)/$', needanerd.views.contactUserForm),

    url(r'^profile/', needanerd.views.profile, name='profile'),
 
    url(r'^$', needanerd.views.home, name='home'),
    url(r'^/$', needanerd.views.home, name='home'),
    url(r'^', 'needanerd.views.notfound', name='404'),
]

needanerd/models.py
#from django.db import models
from django import forms

# import the logging library
import logging
# Get an instance of a logger
logger = logging.getLogger('NeedANerd.custom')

SUBJECT_CHOICES = ('general', 'suggestions', 'websites')

class ContactForm(forms.Form):
    first = forms.CharField(max_length=32,required=True,label="First Name")
    last = forms.CharField(max_length=32,required=True,label="Last Name")
    email = forms.EmailField(max_length=32,required=True,label="Email Address")
    subject = forms.CharField(max_length=32,required=True,label="Subject")
    message = forms.CharField(required=True,widget=forms.widgets.Textarea(),label="Message")
    
class ContactUserForm(forms.Form):
    message = forms.CharField(required=True,widget=forms.widgets.Textarea(attrs={'rows':100, 'cols':50}))
    cc_myself = forms.BooleanField(required=False)
    
'''
sclass StudentReview(models.Model):
    
    CHOICES=[(i+1,i+1) for i in range(5)]
    rating = models.IntegerField(choices=CHOICES)
    comments = models.CharField(max_length=128)
    student = models.ForeignKey('student.Student', blank=False)
    employer = models.ForeignKey('employer.Employer', blank=False)
    created_at = models.DateTimeField(auto_now_add = True)
    
class StudentReviewForm(forms.ModelForm):

    CHOICES=[(i+1, str(i+1)+ " Star(s)") for i in range(5)]
    rating = forms.ChoiceField(choices=CHOICES, widget=forms.Select())
    comments = forms.CharField(label = "Comments", widget=forms.widgets.Textarea(attrs={'rows':3, 'cols':40}), help_text = _("Details about the Student"))
    
    class Meta:
        model = StudentReview
        exclude = ("student","employer",)
        
class EmployerReview(models.Model):
    
    CHOICES=[(i+1,i+1) for i in range(5)]
    rating = models.IntegerField(choices=CHOICES)
    comments = models.CharField(max_length=128)
    student = models.ForeignKey('student.Student', blank=False)
    employer = models.ForeignKey('employer.Employer', blank=False)
    created_at = models.DateTimeField(auto_now_add = True)
    
class EmployerReviewForm(forms.ModelForm):

    CHOICES=[(i+1, str(i+1)+ " Star(s)") for i in range(5)]
    rating = forms.ChoiceField(choices=CHOICES, widget=forms.Select())
    comments = forms.CharField(label = "Comments", widget=forms.widgets.Textarea(attrs={'rows':3, 'cols':40}), help_text = _("Details about the Employer"))
    
    class Meta:
        model = StudentReview
        exclude = ("student","employer",)
'''

needanerd/views.py
#from django.contrib.auth.decorators import login_required
#from django.core.context_processors import csrf
#from django.core.paginator import Paginator, InvalidPage, EmptyPage
#from django.core.urlresolvers import reverse
from job.models import Job
from smtplib import SMTPException
from needanerd.models import ContactForm, ContactUserForm
#rom resume.models import *
#from student.models import *
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
#from django.core import serializers
#from django.db.models import Q 
from django.shortcuts import get_object_or_404
from django.shortcuts import render_to_response
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required, user_passes_test
from django.template import RequestContext
#from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.models import User
from django.utils import timezone
#from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail, mail_admins
from django.conf import settings

from needanerd import studentgroupname, employergroupname

#import datetime, random, sha
#import operator
# import the logging library
import logging
# Get an instance of a logger
logger = logging.getLogger('NeedANerd.custom')

def isAdmin(user):
    if user.is_staff:
        return True
    else:
        return False
    
def home(request):
    
    logger.debug('Home page accessed')
    
    msg = request.session.get('msg')
    if msg:
        logger.debug('Message: ' + msg)
        del request.session['msg']
    else:
        logger.debug('No message')
        if not request.user.is_authenticated():
            msg = 'Employers must register through email'
        
    #Show the 5 latest job postings if they are available
    if Job.objects.count() > 6:
        j=Job.objects.filter(released=True).order_by('-updated_at')[:6]
        logger.debug('Found ' + str(len(j)) + ' objects' )
    elif Job.objects.count() > 0:
        j=Job.objects.filter(released=True).order_by('-updated_at')[:Job.objects.count()]
        logger.debug('Found ' + str(len(j)) + ' objects' )
    else:
        j=None
    
    
    #if 'appsecurity.views.isAdmin'(request.user):
    #    return render_to_response('index.html', {'admin': True, 'jobs': j}, context_instance=RequestContext(request))
    #else:
    return render_to_response('index.html', {'msg': msg, 'jobs': j}, context_instance=RequestContext(request))

def isStudent(user):
    if user.groups.filter(name=studentgroupname).count() > 0:
        logger.debug('User is in the student group')
        return True
    else:
        logger.debug('User is a not in the student group')
        return False

def isEmployer(user):
    if user.groups.filter(name=employergroupname).count() > 0:
        logger.debug('User is in the employer group')
        return True
    else:
        logger.debug('User is a not in the employer group')
        return False

def profile(request):
    
    logger.debug('profile called')
   
    if isStudent(request.user):
        logger.debug('userprofile pk=%s',request.user.userprofile.pk)
        return HttpResponseRedirect('/students/profile/')
    elif isEmployer(request.user):
        logger.debug('userprofile pk=%s',request.user.userprofile.pk)
        return HttpResponseRedirect('/employers/profile/')
    else:
        logger.debug('userprofile is neither student nor employer, discuss amongst yourselves')
        return HttpResponseRedirect(reverse_lazy('home'))

def notfound(request):
    return render_to_response('404.html',context_instance=RequestContext(request))

def contact(request):
    
    if request.method == 'POST': # If the form has been submitted...
        logger.debug('request.method == POST')
        
        form = ContactForm(data=request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            logger.debug('contact form filled out correctly')
            first = form.cleaned_data['first']
            last = form.cleaned_data['last']
            email = form.cleaned_data['email']
            subject = " message: " + form.cleaned_data['subject']
            message = "Message from " + first + " " + last + "\nEmail: " + email + "\n\n" + form.cleaned_data['message']
            
            try:
                
                mail_admins(subject, message)
                logger.debug('Mail send to all admins, ok')
                subject="Thank You For Contacting NeedaNerd"
                confirmation="This is an automated message. You have contacted need a nerd through the online form. Please wait for a response. Thank You"
                send_mail(subject, confirmation, settings.DEFAULT_FROM_EMAIL, email.split())
                
            except SMTPException, err:
                logger.debug('Mail send error: %s', err)
            
            request.session['msg'] = 'You have successfully contacted Need a Nerd, we will respond shortly'    
            return HttpResponseRedirect(reverse_lazy('profile')) # Redirect after POST
        
        else:
            return render_to_response('contactbsform.html', {'user': request.user, 'form': form}, context_instance=RequestContext(request))

    '''    
    else:
        if request.user.is_authenticated():
            form = ContactForm() # An unbound form
            form.fields['sender'].initial=request.user.email
        else:
            form = ContactForm() # An unbound form
    '''
    return render_to_response('contactbsform.html', {
        'user': request.user},
        context_instance=RequestContext(request))
    
@login_required
def contactUserForm(request, user_id):
    
    logger.debug('contactUserForm called')
    receiver=get_object_or_404(User, pk=user_id)
    user=get_object_or_404(User, pk=request.user.pk)
    logger.debug('request.user.username ' + request.user.email)
    
    if request.method == 'POST': # If the form has been submitted...
        logger.debug('request.method == POST')
        form = ContactUserForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            logger.debug('contact form filled out correctly')
            subject = settings.EMAIL_SUBJECT_PREFIX
            subject += " message from "
            subject += request.user.username
            message = form.cleaned_data['message']
            'For whatever reason I could not obtain the values from the form so well just reinsert them here'
            recipients = [receiver.email]
            cc_myself = form.cleaned_data['cc_myself']
            
            if cc_myself:
                recipients.append(user.email)
                
            from django.core.mail import send_mail
            send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, recipients)
            
            request.session['msg'] = 'Email sent successfully!'
            return HttpResponseRedirect(reverse_lazy('profile')) # Redirect after POST
    '''
    else:
        if request.user.is_authenticated():
            form = ContactUserForm() # An unbound form
    return render_to_response('contactuser.html', {
        'form': form, 'user':user},
        context_instance=RequestContext(request))
    '''
    return render_to_response('contactuser.html', {
        'receiver': receiver, 'user':user},
        context_instance=RequestContext(request))
    

needanerd/templates/Copy of need_a_nerd_base.html
<html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="keywords" content="" />
<meta name="description" content="" />
<script type='text/javascript' src='/static/js/jquery-ui-1.10.3/jquery-1.9.1.js'></script>
<script type='text/javascript' src='/static/js/jquery-ui-1.10.3/ui/jquery-ui.js'></script>
<script type='text/javascript' src='/static/js/jquery.json-2.4.min.js'></script> 
<script type='text/javascript' src='/static/js/needanerd.js'></script>
<script type='text/javascript' src='/static/js/job.js'></script>
<script type='text/javascript' src='/static/js/student.js'></script>
<script type='text/javascript' src='/static/js/resume.js'></script>
<link href="/static/css/needanerd.css" rel="stylesheet" />
<link href="/static/css/resume.css" rel="stylesheet" />
<link href="/static/css/jquery-ui.css" rel="stylesheet" />
<link href="/static/css/jquery.ui.datepicker.css" rel="stylesheet" />
<title>{% block header %}Need A Nerd{% endblock %}</title>
</head>

<body>
<!-- start header -->
<div id="header">
	<div id="logo">
		<h1>Need A Nerd</h1>
	</div>	
	
	<div id="menu">
		<ul>
			<li class="active"><a href="/">Home</a></li>
			{% if user.is_authenticated %}
				<li><a href="/profile/">Profile</a></li>
				<!--
				<li><a href="/nerdnews/">Nerd News</a></li>
				-->
				{% if user.userprofile.student %}
					<li><a href="/jobs/apply/">Find Work</a></li>
					<li><a href="/employers/">Find Employers</a></li>
				{% endif %}	
				{% if user.userprofile.employer %}
					<li><a href="/students/">Find Students</a></li>
					<li><a href="/jobs/list/">View All Job Listings</a></li>
				{% endif %}
				<li><a href="/contact/">Contact</a></li>					
				<li><a href="/accounts/logout/">Logout</a></li>
			{% else %}
				<li><a href="/contact/">Contact</a></li>			
				<li><a href="/accounts/login/">Login</a></li>
			{% endif %}
		</ul>
	</div>
</div>
<hr />
<!-- end header -->

	<!-- <h2>{% block title %}Need A Nerd{% endblock %}</h2>  -->
    
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    
    {% if user.is_authenticated %}
    	<p>You are currently logged in as {{ user.username }}. Thanks for using NeedaNerd.</p>	    	    	
	{% else %}
    	<p>Welcome to NeedaNerd, please log in or register for a new account</p>
    	<p>
		<ul>
			<li><a href='/students/register/'>Register as a Student</a></li>
			<li><a href='/employers/register/'>Register as an Employer</a></li>
		</ul>
		</p>    
	{% endif %}
<!-- <p><a href='/'>Need a Nerd Home</a></p> -->
<div id="acctmanagement">
        {% block acctmanagement %}{% endblock %}
</div>
<div id="footer">
<p id="legal"> &copy;2012 Auburn University. All Rights Reserved.
</p>
<p id="rss">Want to know the latest jobs in an ATOM feed? Use the link <a href="/feeds/">here</a> to get the latest Need a Nerd jobs</p>
<p id="rss"><img src="/static/css/images/auburn_logo.jpg" alt="Auburn University" height="100" width="100"/></p>
<!-- end footer -->
</div> 
</body>
</html>

needanerd/templates/bstemplate.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

    <title>Need a Nerd</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/justified-nav.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <div class="masthead">
        <h3 class="text-muted">Welcome to Need a Nerd</h3>
        <ul class="nav nav-justified">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">Profile</a></li>
          <li><a href="#">Find Nerds</a></li>
          <li><a href="#">Find Jobs</a></li>
          <li><a href="#">Contact</a></li>
          <li><a href="#">Login</a></li>
        </ul>
      </div>

      <!-- Jumbotron -->
      <div class="jumbotron">
        <h1>Nerdsville!</h1>
        <p class="lead">Need a Nerd is the best spot for nerds to find cuttng edge jobs, and employers to find grade A talent.</p>
        <p><a class="btn btn-lg btn-success" href="#" role="button">Get Started</a></p>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="col-lg-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-lg-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-lg-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
          <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>	
		 
      <!-- Site footer -->
      <div class="footer">
        <p>&copy; Need a Nerd</p>
      </div>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type='text/javascript' src='/static/js/jquery-ui-1.10.3/jquery-1.9.1.js'></script>
    <script src="/static/js/bootstrap.min.js"></script>
  </body>
</html>

needanerd/templates/contactbsform.html
{% extends "need_a_nerd_base.html" %}

{% block title %}Contact Need a Nerd{% endblock %}

{% block content %}

{% if form.errors %}
	<br/>
    {% for field in form %}
        {% for error in field.errors %}
           		<div class="alert alert-danger">
                <strong>{{ error|escape }}: {{field.label}}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
     		<div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<br/>
<div class="container" width="90%" >
	<form class="well span8" method="post" >
		{% csrf_token %}
        <div class="row">
            <div class="col-md-3">
                <label>First Name:</label><br/><input name="first" id="first" class="span3" placeholder="Your First Name" type="text">
                <br/><br/><label>Last Name:</label><br/><input name="last" id="last" class="span3" placeholder="Your Last Name" type="text">
                <br/><br/><label>Email Address:</label><br/><input name="email" id="email" class="span3" placeholder="Your email address" type="text">
                <br/><br/><label>Subject: </label><br/>
                <select class="span3" id="subject" name="subject">
                    <option value="general">
                        General
                    </option>
    
                    <option value="suggestions">
                        Suggestions
                    </option>
    
                    <option value="website">
                        Website Problems
                    </option>
                </select>
            </div>
    
            <div class="col-md-6">
                <label>Message:</label><textarea class="form-control" id="message" name="message" rows="10"></textarea>
                <br/>
                <button class="btn btn-primary pull-right" type="submit">Send</button>
            </div>            
        </div>
    </form>
</div>

{% endblock %}

needanerd/templates/contactuser.html
{% extends "need_a_nerd_base.html" %}

{% block title %}Contact Need a Nerd{% endblock %}

{% block content %}

{% if form.errors %}
	<br/>
    {% for field in form %}
        {% for error in field.errors %}
           		<div class="alert alert-danger">
                <strong>{{ error|escape }}: {{field.label}}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
     		<div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<br/>

	<form class="well span8" method="post" >
		
		{% csrf_token %}
		
		{% if receiver.first_name %}
			<p>Contacting {{ receiver.first_name }} {{ receiver.last_name }}</p>
		{% elif user.userprofile.employer.company_name %}
			<p>Contacting {{user.userprofile.employer.company_name}}</p>
		{% endif %}
		
		<div class="row">
            <div class="col-md-4">
                <label for="id_subject" class="control-label">Subject:</label><input id="id_subject" name="subject" class="form-control" placeholder="Subject" type="text"/>
            </div>
            <br/>
            <div class="col-md-4">
                <label for="id_cc_myself" class="control-label">Copy Myself:</label><input id="id_cc_myself" name="cc_myself" type="checkbox" />
            </div>
    	</div>
    	<div class="row">
            <div class="col-md-10">
                <label>Message:</label><textarea class="form-control" id="id_message" name="message" rows="10"></textarea>
                <br/>
                <button class="btn btn-primary pull-left" type="submit">Send</button>
            </div>            
        </div>
    </form>

{% endblock %}

needanerd/templates/index.html
{% extends "need_a_nerd_base.html" %}

{% block title %}{% endblock %}

{% block content %}

{% if admin %}
<div>
	<ul>
		<li><a href="/students/">View all Students</a></li>
		<li><a href="/employers/">View all Employers</a></li>
		<li><a href="#" onclick="confirmDelete( {{user.pk}} )">Unregister</a> with Need a Nerd</li>
		<li><a href="/accounts/passwordchange/">Change</a> your password</li>
	</ul>
</div>		
{% endif %}

{% if not user.is_authenticated %}

      <div class="container">
   
       <div class="omb_login">
    			<div class="row omb_row-sm-offset-3 omb_socialButtons">
    	    <div class="col-xs-4 col-sm-2 visible-md visible-lg">
		        <a href="{% url 'social:begin' backend='facebook' %}" class="btn btn-lg btn-block btn-social btn-facebook">
    				<span class="fa fa-facebook"></span> Facebook &nbsp;&nbsp;&nbsp;
  				</a>
	        </div>
        	<div class="col-xs-4 col-sm-2 visible-md visible-lg">
		        <a href="{% url 'social:begin' backend='linkedin-oauth2' %}" class="btn btn-lg btn-block btn-social btn-linkedin">
    				<span class="fa fa-linkedin"></span> LinkedIn &nbsp;&nbsp;&nbsp;
  				</a>
	        </div>	
        	<div class="col-xs-4 col-sm-2 visible-md visible-lg">
  				<a href="{% url 'social:begin' backend='google-oauth2' %}" class="btn btn-lg btn-block btn-social btn-google">
            		<span class="fa fa-google-plus"></span> Google+ &nbsp;&nbsp;&nbsp;
            	</a>
	        </div>
	        <div class="col-xs-4 col-sm-2 visible-xs visible-sm">
		        <a href="{% url 'social:begin' backend='facebook' %}" class="btn btn-lg btn-block btn-social-icon btn-facebook"><span class="fa fa-facebook"></span></a>
	        </div>
        	<div class="col-xs-4 col-sm-2 visible-xs visible-sm">
		        <a href="{% url 'social:begin' backend='linkedin-oauth2' %}" class="btn btn-lg btn-block btn-social-icon btn-linkedin"><span class="fa fa-linkedin"></span></a>
		    </div>	
        	<div class="col-xs-4 col-sm-2 visible-xs visible-sm">
  				<a href="{% url 'social:begin' backend='google-oauth2' %}" class="btn btn-lg btn-block btn-social-icon btn-google"><span class="fa fa-google-plus"></span></a>
	        </div>
		</div>
		
		<form class="form-signin" method="post" action="/accounts/login/">
      {% csrf_token %}
      
        <!-- <h2 class="form-signin-heading">Sign in</h2>  --> 
        <input name="username" type="text" class="form-control" placeholder="Email" required autofocus/>
        <input name="password" type="password" class="form-control" placeholder="Password" required/>
        {% if nexturl %}
        	<input type="hidden" name="next" value="{{nexturl}}" />
        {% endif %}
        <label class="checkbox">
          <input type="checkbox" value="rememberme"/> Remember me
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>

        <br/><br/>
        <button class="btn btn-lg btn-primary btn-block" data-toggle="modal" data-target="#myModal">
		        Not Registered?
	        </button>
			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
			    <div class="modal-content">
			      <div class="modal-footer">
			      	<center>
				      	Register me as an: <br/>
				        <button type="button" id='nerdregbutton' class="btn btn-primary">Official Nerd</button>
				        <button type="button" id='employerregbutton' class="btn btn-primary">Employer of Nerds</button>
			        </center>
			      </div>
			    </div>
			  </div>
			</div>
		<br/>
		<a href="{{BASE_URL}}/accounts/password/reset/">Forget your password?</a>
		<br/>		
      </form>
      
		<br/>
				
	</div>



        </div>
{% else %}

	{% if jobs %}
		<div class="row">
	    {% for j in jobs %}
			<div class="col-lg-4">
	          <h3>{{j.name}}</h3>
	          <p class="frontpagejobdesc">{{j.description}}</p>
	          <p><a class="btn btn-primary" href="/jobs/{{j.pk}}" role="button">View details &raquo;</a></p>
	        </div>
	     {% endfor %}
	    </div>
	{% else %}
		<!--Need a Nerd does not have any jobs in its database-->
	{% endif %}

{% endif %}

{% endblock %}