job/urls.py
from django.conf.urls import url
import job.views

urlpatterns = [
    
    #url(r'^$', 'job.views.jobs'),
    url(r'^(?P<job_id>\d+)/$', job.views.job_detail),
    url(r'^(?P<job_id>\d+)/applicants/$', job.views.applicantlist),
    url(r'^add/$', job.views.jobForm),
    url(r'^edit/(?P<job_id>\d+)/$', job.views.editJobForm),
    url(r'^apply/$', job.views.applyJob),
    url(r'^search/$', job.views.jobsearch),
    url(r'^list/(?P<student_id>\d+)/$', job.views.jobList),
    url(r'^delete/(?P<job_id>\d+)/$', job.views.deleteJob),
       
]
    

needanerd/urls.py
from django.conf.urls import url, include
import needanerd.views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

permission_denied_url = '/denied/'

urlpatterns = [
               
    # (r'^test/', TemplateView.as_view(template_name="bstemplate.html")),
    url(r'^students/', include('student.urls')),
    url(r'^employers/', include('employer.urls')),
    url(r'^jobs/', include('job.urls')),
    url(r'^resumes/', include('resume.urls')),
    url(r'^accounts/', include('appsecurity.urls')),
    #url(r'^messages/', include('msgcenter.urls')),
    
    url(r'^contact/$', needanerd.views.contact),
    url(r'^contact/(?P<user_id>\d+)/$', needanerd.views.contactUserForm),

    url(r'^profile/', needanerd.views.profile, name='profile'),
 
    url(r'^$', needanerd.views.home, name='home'),
    url(r'^/$', needanerd.views.home, name='home'),
    url(r'^', 'needanerd.views.notfound', name='404'),
]

student/urls.py
from django.conf.urls import url
import student.views

urlpatterns = [
    
    url(r'^$', student.views.students),
    url(r'^(?P<student_id>\d+)/$', student.views.student_detail),
    url(r'^profile/$', student.views.student_profile),
    url(r'^search/$', student.views.studentsearch),
    url(r'^edit/(?P<student_id>\d+)/$', student.views.editStudentForm),
    url(r'^update/(?P<student_id>\d+)/$', student.views.updateStudent),
    url(r'^apply/(\d+)/(\d+)/$', student.views.studentApplication),
    url(r'^register/$', student.views.studentForm)
    #url(r'^review/(?P<user_id>\d+)/$', 'student.views.studentReviewForm'),
    
]

resume/models.py
from django.db import models
#from django import forms
from django.contrib import admin

# import the logging library
import logging
# Get an instance of a logger
logger = logging.getLogger('NeedANerd.custom')

class Resume(models.Model):
    student=models.ForeignKey('student.Student')
    objective=models.TextField(blank=True)

admin.site.register(Resume)

class Degree(models.Model):
    resume=models.ForeignKey('resume.Resume')
    degreetype=models.CharField(max_length=32, blank=True)
    major=models.CharField(max_length=32, blank=True)
    university=models.CharField(max_length=32, blank=False)
    '''Not using DateField because it expects a certain format which is only overridden with widgets (forms) which we are not using'''
    date=models.CharField(max_length=16, blank=True,null=True)
    gpa=models.CharField(max_length=8,blank=True)
    honors=models.CharField(max_length=16,blank=True)

admin.site.register(Degree)

class Skill(models.Model):
    resume=models.ForeignKey('resume.Resume')
    skill=models.CharField(max_length=32)

admin.site.register(Skill)

class Certification(models.Model):
    resume=models.ForeignKey('resume.Resume')
    name=models.CharField(max_length=32)
    authority=models.CharField(max_length=32, blank=True)
    licnumber=models.CharField(max_length=32, blank=True)
    url=models.CharField(max_length=128, blank=True)
    expdate=models.CharField(max_length=16, blank=True,null=True)
    neverexp=models.BooleanField(blank=True)
    
admin.site.register(Certification)

class Employment(models.Model):
    resume=models.ForeignKey('resume.Resume')
    company=models.CharField(max_length=64)
    title=models.CharField(max_length=64)
    startdate=models.CharField(max_length=16, blank=True,null=True)
    enddate=models.CharField(max_length=16, blank=True,null=True)
    jobfunctions=models.TextField(max_length=256)

admin.site.register(Employment)
'''
class ResumeForm(forms.ModelForm):
    class Meta:
        model = Resume
        exclude = ('student',)
    
    objective = forms.CharField(required=False, label="Objective", widget=forms.widgets.Textarea(attrs={'rows':15, 'cols':100}))

class ResumeEditForm(forms.ModelForm):
    class Meta:
        model = Resume
        fields = ("objective",)
    
    objective = forms.CharField(required=False, label="Objective", widget=forms.widgets.Textarea(attrs={'rows':15, 'cols':100}))

    def save(self):
        
        logger.debug('Saving Resume')
        logger.debug('self.instance.pk='+str(self.instance.pk))
        
        resume=Resume.objects.get(pk=self.instance.pk)
        resume.body=self.cleaned_data["body"]
        resume.save()
        
        return resume

class SkillsForm(forms.ModelForm):
    class Meta:
        model = Skill
        exclude = ("resume",)
 
class DegreeForm(forms.ModelForm):
    
    date = forms.DateField(label = "Date: (Format: DD/MM/YYYY)")
    degreetype = forms.CharField(label = "Type (i.e. B.S., B.A.)", max_length=32)
    gpa = forms.CharField(label = "G.P.A.", max_length=32)
    honors = forms.CharField(label = "Honors", max_length=32)
    
    class Meta:
        model = Degree
        exclude = ("resume",)
        
    def save(self, r):
        
        logger.debug('Saving Degree')
        logger.debug('self.instance.pk='+str(self.instance.pk))
        degree=Degree(resume=r)
        degree.degreetype=self.cleaned_data["degreetype"]
        degree.major=self.cleaned_data["major"]
        degree.university=self.cleaned_data["university"]
        degree.date=self.cleaned_data["date"]
        degree.gpa=self.cleaned_data["gpa"]
        degree.honors=self.cleaned_data["honors"]
        degree.save()
        return degree
    
class DegreeEditForm(forms.ModelForm):
    
    date = forms.DateField(label = "Date: (Format: DD/MM/YYYY)")
    degreetype = forms.CharField(label = "Type (i.e. B.S., B.A.)", max_length=32)
    gpa = forms.CharField(label = "G.P.A.", max_length=32)
    honors = forms.CharField(label = "Honors", max_length=32)
    
    class Meta:
        model = Degree
        exclude = ("resume",)
    
    def save(self):
        
        logger.debug('Saving Degree')
        logger.debug('self.instance.pk='+str(self.instance.pk))
        degree=Degree.objects.get(pk=self.instance.pk)
        degree.degreetype=self.cleaned_data["degreetype"]
        degree.major=self.cleaned_data["major"]
        degree.university=self.cleaned_data["university"]
        degree.date=self.cleaned_data["date"]
        degree.gpa=self.cleaned_data["gpa"]
        degree.honors=self.cleaned_data["honors"]
        degree.save()
        return degree

class SkillForm(forms.ModelForm):
    class Meta:
        model = Skill
        exclude = ("resume",)
        
class SkillEditForm(forms.ModelForm):
    class Meta:
        model = Degree
        exclude = ("resume",)
        
    def save(self):
        
        logger.debug('Saving Degree')
        logger.debug('self.instance.pk='+str(self.instance.pk))
        skill=Degree.objects.get(pk=self.instance.pk)
        skill.skill=self.cleaned_data["skill"]
        skill.save()
        return skill
    
class CertificationForm(forms.ModelForm):
    class Meta:
        model = Certification
        exclude = ("resume",)
        expdate = forms.DateField(input_formats='%m/%Y') #Only care about month and year
        
class CertificationEditForm(forms.ModelForm):
    class Meta:
        model = Certification
        exclude = ("resume",)
        expdate = forms.DateField(input_formats='%m/%Y') #Only care about month and year
        
    def save(self):
        
        logger.debug('Saving Degree')
        logger.debug('self.instance.pk='+str(self.instance.pk))
        certification=Degree.objects.get(pk=self.instance.pk)
        certification.certification=self.cleaned_data["certification"]
        certification.vendor=self.cleaned_data["vendor"]
        certification.save()
        return certification

class EmploymentForm(forms.ModelForm):
    
    class Meta:
        model = Employment
        exclude = ("resume",)
        startdate = forms.DateField(input_formats='%m/%Y') #Only care about month and year
        enddate = forms.DateField(input_formats='%m/%Y') #Only care about month and year

    def save(self, resumepk):
        
            if self.instance.pk:
                employment=Employment.objects.get(pk=self.instance.pk)
            else:
                employment = Employment()
                
            employment.r=Resume.objects.get(pk=resumepk)
            employment.company=self.cleaned_data['company']
            employment.title=self.cleaned_data['title']
            employment.startdate=self.cleaned_data['startdate']
            employment.enddate=self.cleaned_data['enddate']
            employment.jobfunctions=self.cleaned_data['jobfunctions']
            employment.save()

class EmploymentEditForm(forms.ModelForm):
    
    class Meta:
        model = Employment
        exclude = ("resume",)
        startdate = forms.DateField(input_formats='%m/%Y') #Only care about month and year
        enddate = forms.DateField(input_formats='%m/%Y') #Only care about month and year

    def save(self, resumepk):
        
            if self.instance.pk:
                employment=Employment.objects.get(pk=self.instance.pk)
            else:
                employment = Employment()
                
            employment.r=Resume.objects.get(pk=resumepk)
            employment.company=self.cleaned_data['company']
            employment.title=self.cleaned_data['title']
            employment.startdate=self.cleaned_data['startdate']
            employment.enddate=self.cleaned_data['enddate']
            employment.jobfunctions=self.cleaned_data['jobfunctions']
            employment.save()
'''

student/models.py
#from django.contrib.auth.models import User
from django.db import models
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User, Group
from django.contrib import admin
from resume.models import Resume
from needanerd import studentgroupname

# import the logging library
import logging
# Get an instance of a logger
logger = logging.getLogger('NeedANerd.custom')

class Student(models.Model):
    
    userprofile=models.OneToOneField('appsecurity.UserProfile',primary_key=True)
    currentmajor=models.CharField(max_length=32)

admin.site.register(Student)

'''This class is used to serialize a JSON response back to the user through the search REST functions'''
class StudentSearch(models.Model):
    studentid=models.IntegerField()
    first_name=models.CharField(max_length=32)
    last_name=models.CharField(max_length=32)
    currentmajor=models.CharField(max_length=32)
    objective=models.TextField(blank=True)
    
class StudentUserCreationForm(forms.ModelForm):
    
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'duplicate_email': _("This email is already registered to an account, either retrieve your password or use a new email"),
        'password_mismatch': _("The two password fields didn't match."),
    }
    
    email = forms.EmailField(label = "Email", max_length=32)
    first_name = forms.CharField(label = "First name", max_length=16)
    last_name = forms.CharField(label = "Last name", max_length=32)
    currentmajor = forms.CharField(label = "Current Academic Major", max_length=32)
    ''' 
    username = forms.RegexField(label=_("Username"), max_length=32,
        regex=r'^[\w.@+-]+$',
        help_text = _("Required. 30 characters or fewer. Letters, digits and "
                      "@/./+/-/_ only."),
        error_messages = {
            'invalid': _("This value may contain only letters, numbers and "
                         "@/./+/-/_ characters.")})'''
    password1 = forms.CharField(label=_("Password"),
        widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"),
        widget=forms.PasswordInput,
        help_text = _("Enter the same password as above, for verification."))

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email","currentmajor",)
    '''
    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])
    '''
    def clean_email(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        email = self.cleaned_data["email"]
        try:
            User.objects.get(username=email)
        except User.DoesNotExist:
            return email
        raise forms.ValidationError(self.error_messages['duplicate_email'])
    
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1", "")
        password2 = self.cleaned_data["password2"]
        if password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'])
        return password2

    def save(self):
        user = super(StudentUserCreationForm, self).save(commit=False)
        user.is_active=False
        user.set_password(self.cleaned_data["password1"])
        user.username=(self.cleaned_data["email"])
        
        'We have to save here so the userprofile is created'
        user.save()
        logger.debug('Saving user with username: '+user.username)
        
        newStudent=Student(currentmajor=self.cleaned_data["currentmajor"])
        newStudent.userprofile=user.userprofile
        newStudent.save()
        
        'Create a default resume'
        Resume.objects.create(student=newStudent)
        
        user.userprofile.student=newStudent
        user.userprofile.save()
        studentgroup = Group.objects.get_or_create(name=studentgroupname)
        user.groups.add(studentgroup[0])

        user.save()
        return user
    
class StudentUserEditForm(forms.ModelForm):
    
    first_name = forms.CharField(label = "First name")
    last_name = forms.CharField(label = "Last name")
    currentmajor = forms.CharField(label = "Current Academic Major")
    
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email","currentmajor",)

    def save(self):
        
        logger.debug('Saving student')
        logger.debug('self.instance.pk='+str(self.instance.pk))
        student=Student.objects.get(pk=self.instance.userprofile.student.pk)
        user=User.objects.get(pk=self.instance.pk)
        
        student.currentmajor=self.cleaned_data["currentmajor"]
        student.save()
        user.first_name=self.cleaned_data["first_name"]
        user.last_name=self.cleaned_data["last_name"]
        user.username=(self.cleaned_data["email"])
        user.email=self.cleaned_data["email"]
        user.save()
        return user

student/templates/editstudent.html
{% extends "need_a_nerd_base.html" %}

{% block title %}Edit Student{% endblock %}

{% block content %}
<form action="/students/edit/{{user.pk}}/" method="post">
{% csrf_token %}
{{ form.as_p }}
<button type="submit" class="btn-lg btn-primary">
	<span class="glyphicon glyphicon-ok-sign"></span> Save Changes
</button>
</form>
{% endblock %}

student/templates/registerStudent.html
{% extends "need_a_nerd_base.html" %}

{% block title %}Register Student{% endblock %}

{% block content %}

<br/>
{% if form.errors %}
	<br/>
    {% for field in form %}
        {% for error in field.errors %}
           		<div class="alert alert-danger">
                <strong>{{ error }}</strong>
                {% if "retrieve" in error %}
                	<a href="{{BASE_URL}}/accounts/password/reset/">Retrieve Password</a>
                {% endif %}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
     		<div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form action="/students/register/" method="post">
{% csrf_token %}
{{ form.as_p }}
<button type="submit" class="btn-lg btn-primary">
	<span class="glyphicon glyphicon-ok-sign"></span> Confirm	
</button>
</form>
{% endblock %}

student/templates/students.html
{% extends "need_a_nerd_base.html" %}

{% block title %}All Students{% endblock %}

{% block content %}
{% if students %}

	<form id='searchstudents'>
		<br/>
		<label for="studentsearchstr" class="control-label">Filter students by name or current major (partial searches accepted):</label>
		<div class="row">	
			<div class="col-md-4">
				<p>
					<input type=text id='studentsearchstr' class="form-control" onkeydown=searchStudents(''+document.getElementById("studentsearchstr").value+'') placeholder="Mark Zuckerberg" />
				</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6">
				<!-- <button class="btn btn-primary" onclick=searchStudents(''+document.getElementById("studentsearchstr").value+'') >Filter Students</button>  -->
				<button class="btn btn-primary" type=submit >Show All Students</button>
			</div>
		</div>
		<br />
	</form>
	<br />
	<div>
	<table id="studentstable" class="table table-striped table-hover table-responsive">
	<tr>
    	<th class="col-md-1">Name</th>
    	<th class="col-md-1">Academic Major</th>
        <th class="col-md-4 visible-sm visible-md visible-lg">Summary</th>
        <th class="col-md-1">Contact Student</th>       
	</tr>
	{% for user in students %}
    	<tr>
        	<td><a href='/students/{{user.pk}}/'>{{user.first_name}} {{user.last_name}}</a></td>
        	<td>{{user.userprofile.student.currentmajor}}</td>
        	<td class="visible-md visible-lg">{%with user.userprofile.student.resume_set.all|first as resume%}{{resume.objective|slice:":512"}}{%endwith%}</td>
        	<td class="visible-sm">{%with user.userprofile.student.resume_set.all|first as resume%}{{resume.objective|slice:":256"}}{%endwith%}</td>
        	<td><a class="btn btn-primary" href="/contact/{{user.pk}}/">Contact</a></td>
    	</tr>
	{% endfor %}
	</table>
	</div>
	<small>
	<p id="top10" class="text-left"></p>
	</small>
	<div id="pagination" class="pagination">
	    <span class="step-links">
	        {% if students.has_previous %}
	            <a href="?page={{ students.previous_page_number }}">Previous</a>
	        {% endif %}
	
	        <span class="current">
	            Page {{ students.number }} of {{ students.paginator.num_pages }}.
	        </span>
	
	        {% if students.has_next %}
	            <a href="?page={{ students.next_page_number }}">Next</a>
	        {% endif %}
	    </span>
	</div>
{% else %}
    There are no students listed in the database.
{% endif %}
{% endblock %}